config/routes.rb
Rails.application.routes.draw do
  root 'twitters#index', as: 'home'
  resources :twitters
  resources :twitters do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twitter.rb
class Twitter < ApplicationRecord
  validates :content, presence: true
  validates :content, length: { in: 1..140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/twitters_controller.rb
class TwittersController < ApplicationController
  before_action :set_twitter, only: [:show, :edit, :update, :destroy]
  def index
    @twitters = Twitter.all
  end

  def new
    @twitter = Twitter.new
  end

  def create
    @twitter = Twitter.new(twitter_params)
    if params[:back]
      render :new
    else
      if @twitter.save
        redirect_to twitters_path, notice: "ツイートしました！"
      else
        render :new
      end
    end
  end

  def confirm
    @twitter = Twitter.new(twitter_params)
    render :new if @twitter.invalid?
  end

  def edit
  end

  def update
    if @twitter.update(twitter_params)
      redirect_to home_path, notice: "ツイートを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @twitter.destroy
    redirect_to twitters_path, notice:"ツイートを削除しました！"
  end


  private
  def twitter_params
    params.require(:twitter).permit(:content)
  end

  def set_twitter
    @twitter = Twitter.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twitters_helper.rb
module TwittersHelper
    def choose_create_or_edit
        if action_name == 'new' || action_name == 'create'
            confirm_twitters_path
        elsif action_name == 'edit'
            twitter_path
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrap">
      <header>
        <ul>
          <li><%= link_to 'つぶやき一覧', twitters_path %></li>
          <li><%= link_to 'つぶやく', new_twitter_path %></li>
        </ul>
      </header>
      <div id="contents">
        <%= yield %>
      </div>
        <footer>
          <p>Rails入門シリーズ課題</p>
        </footer>
      </div>
  </body>
</html>

app/views/twitters/_form.html.erb
<%= form_with(model: @twitter, local: true, url: choose_create_or_edit ) do |form| %>

<% if @twitter.errors.any? %>
  <div id="error_explanation">
    <h2><%= @twitter.errors.count %>件のエラーがあります。</h2>
    <ul>
    <% @twitter.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="twitter_content">
    <%= form.label :content,"ツイート内容" %><br>
    <%= form.text_field(:content,{:class => 'form-control'}) %>
  </div>
  <%= form.submit("ツイートする") %>

<% end %>
<%= link_to 'つぶやき一覧画面に戻る', twitters_path %>

app/views/twitters/confirm.html.erb
<%= form_with(model: @twitter, url: twitters_path, local: true) do |form| %>
    <h3>以下の内容でツイートする。</h3>
    <%= form.hidden_field :content %>
    <p>つぶやき:<%= @twitter.content %></p>
    <%= form.submit  "ツイートする" %>
    <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/twitters/edit.html.erb
<h2>つぶやきを編集する</h2>
<%= render 'form' %>

app/views/twitters/index.html.erb
<h1>つぶやき一覧</h1>
<p><%= notice %></p>
<table>
  <tr>
    <th class="title">つぶやき</th>
  </tr>
<% @twitters.each do |twitter| %>
  <tr>
    <td class="tweet"><%= twitter.content %></td>
    <td><%= link_to "つぶやきを編集する", edit_twitter_path(twitter.id), data: {confirm: "本当に編集していいですか？"} %></td>
    <td><%= link_to "つぶやきを削除する", twitter_path(twitter.id), method: :delete, data: {confirm: "本当に削除していいですか？"} %></td>
  </tr>
<% end %>
</table>

<%= link_to 'つぶやく', new_twitter_path %>

app/views/twitters/new.html.erb
<h2>つぶやく</h2>
<%= render 'form' %>